modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Sunekaer/YAMDA/issues"
[[mods]]
modId="yamda"
version="${file.jarVersion}"
displayName="YAMDA"
displayURL="https://minecraft.curseforge.com/projects/yamda"
authors="Sunekaer"
description='''
Yet Another Mining Dimension Attempt
'''
[[dependencies.yamda]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30.0.7,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.yamda]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"